package com.example.csi5175final;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.FileProvider;

import android.annotation.SuppressLint;
import android.content.ContentResolver;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.ImageDecoder;
import android.graphics.Paint;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffXfermode;
import android.graphics.Rect;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Environment;
import android.os.Handler;
import android.os.Looper;
import android.provider.MediaStore;
import android.provider.Settings;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class GameOver extends AppCompatActivity {

    String current_score = "0";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.game_over);

        //show user score
        Intent intent = getIntent();
        TextView result = findViewById(R.id.score_view);
        current_score = intent.getStringExtra("score");
        String preview = "Your score is:\n " + current_score;
        result.setText(preview);

        //restart game
        Button bt_restart = findViewById(R.id.restart_game);
        bt_restart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //restart game
                startActivity(new Intent(GameOver.this, GameScene.class));
            }
        });

        //share game
        Button bt_share = findViewById(R.id.share_game);
        bt_share.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                makeShareImage();
                shareImage();
            }
        });

        //save user current score
        Button bt_saveScore = findViewById(R.id.save_current_score);
        bt_saveScore.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //get user id
                ContentResolver contentResolver = getContentResolver();
                @SuppressLint("HardwareIds") String android_id = Settings.Secure.getString(contentResolver,
                        Settings.Secure.ANDROID_ID);
                //post user current score to server
                int score = Integer.parseInt(current_score);
                postScore(android_id, score);
            }
        });

        //back to lobby
        Button bt_leave = findViewById(R.id.leave_game);
        bt_leave.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //restart game
                startActivity(new Intent(GameOver.this, HomePage.class));
            }
        });
    }

    /**
     * function for getting the bitmap for sharing.
     *
     * @return bitmap generated by the app.
     */
    private void makeShareImage(){
        //get template from resource
        Drawable shareTmp = getDrawable(R.drawable.share);
        Bitmap shareImg = ((BitmapDrawable) shareTmp).getBitmap();
        android.graphics.Bitmap.Config bitmapConfig = shareImg.getConfig();
        // set default bitmap config if none
        if(bitmapConfig == null) {
                bitmapConfig = android.graphics.Bitmap.Config.ARGB_8888;
        }
        // convert resource bitmaps are to mutable one
        shareImg = shareImg.copy(bitmapConfig, true);
        Canvas canvas = new Canvas(shareImg);
        //set up paint brush
        Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        paint.setColor(Color.BLACK); // Text Color
        paint.setTextSize(100); // Text Size
        // draw text to the bitmap
        canvas.drawText("Your score is:", 250, 1350, paint);
        canvas.drawText(current_score, 500, 1450, paint);
        // save bitmap to cache directory
        try {

            File cachePath = new File(GameOver.this.getCacheDir(), "images");
            cachePath.mkdirs(); // don't forget to make the directory
            FileOutputStream stream = new FileOutputStream(new File(cachePath, "image.png")); // overwrites this image every time
            shareImg.compress(Bitmap.CompressFormat.PNG, 100, stream);
            stream.close();

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * function for sharing the PNG image from Uri.
     */
    private void shareImage(){
        File imagePath = new File(GameOver.this.getCacheDir(), "images");
        File newFile = new File(imagePath, "image.png");
        Uri contentUri = FileProvider.getUriForFile(GameOver.this, "com.example.csi5175final.provider", newFile);

        if (contentUri != null) {
            Intent intent = new Intent(android.content.Intent.ACTION_SEND);
            intent.putExtra(Intent.EXTRA_STREAM, contentUri);
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            intent.setType("image/png");
            startActivity(intent);
        }
    }

    //setup menu bar
    @Override
    public boolean onCreateOptionsMenu(Menu menu){
        // back to homepage setting
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.menu_bar, menu);
        return true;
    }
    //setup actions for each selections
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle item selection
        switch (item.getItemId()) {
            case R.id.toggleMusic: //TODO: add toggle music feature
                Intent intent_file = new Intent(Intent.ACTION_GET_CONTENT);
                intent_file.setType("audio/*");
                intent_file.addCategory(Intent.CATEGORY_OPENABLE);

                Intent finalIntent = Intent.createChooser(intent_file, "Select background music");

                startActivityForResult(finalIntent, 1);
                return true;
            case R.id.backHome: //back to lobby
                startActivity(new Intent(GameOver.this, HomePage.class));
                return true;
            case R.id.quitGame: // close the app
                Intent intent = new Intent(Intent.ACTION_MAIN);
                intent.addCategory(Intent.CATEGORY_HOME);
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(intent);
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    //post user current score to the database
    private void postScore(String id, int score){
        ExecutorService executor = Executors.newSingleThreadExecutor();
        Handler handler = new Handler(Looper.getMainLooper());

        executor.execute(new Runnable() {
            @Override
            public void run() {
                try{
                    String url = "HTTP://18.191.10.52:3000/score";
                    String urlParameters  = "id="+id+"&num2=" + score;
                    InputStream stream = null;
                    byte[] postData = urlParameters.getBytes( StandardCharsets.UTF_8 );
                    int postDataLength = postData.length;
                    URL urlObj = new URL(url);
                    HttpURLConnection conn = (HttpURLConnection) urlObj.openConnection();
                    conn.setDoOutput(true);
                    conn.setRequestMethod("POST");
                    conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
                    conn.setRequestProperty("charset", "utf-8");
                    conn.setRequestProperty("Content-Length", Integer.toString(postDataLength ));
                    conn.setReadTimeout(10000);
                    conn.setConnectTimeout(15000);

                    conn.connect();

                    try(DataOutputStream wr = new DataOutputStream(conn.getOutputStream())) {
                        wr.write( postData );
                        wr.flush();
                    }

                    stream = conn.getInputStream();
                    BufferedReader reader = new BufferedReader(new InputStreamReader(stream, "UTF-8"), 8);
                    String result = reader.readLine();

                } catch (Exception e) {
                    e.printStackTrace();
                }

                handler.post(new Runnable() {
                    @Override
                    public void run() {
                        Toast.makeText(GameOver.this, R.string.post_score, Toast.LENGTH_LONG).show();
                    }
                });
            }
        });
    }
}